### ISSUE TITLE
Will this ever be integrated with Serde?

### ISSUE THREAD

**Issue by loganintech** [sinistersnare/ds_store#2]

**Comment by sinistersnare** [comment]
Hi, `.DS_Store` files are not for storing arbitrary data. I plan on adding APIs for manipulating these files, but they probably should not be related to Serde.

Do you have an example of something that we could do in this library with Serde? If so, I would love to add something.

**Comment by loganintech** [comment]
I don't have a specific example aside from possible generic programs that take type T where T: Deserialize.

**Comment by sinistersnare** [comment]
Because .DS_Store files do not take arbitrary data, I am not sure this library could accommodate that. There is no place in the file format for such arbitrary data, is all. Because of that I will close the issue. If you think of a way to do this that still allows Finder to read these files, please file another issue, I would love to work on it.

Thank you for making this issue, and giving me the opportunity to think on this feature. It gave me a better understanding of the .DS_Store format, so it was very helpful :)
